---

- name: Install dependencies
  apt:
    name: openjdk-8-jdk

- name: Create Cakeshop directory
  file:
    path: '{{ project_path }}/../cakeshop'
    state: directory
    mode: '0755'

- name: Correct java version selected
  alternatives:
    name: java
    path: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java

- name: Download Cakeshop
  get_url:
    url: https://github.com/alastria/cakeshop/releases/download/v0.10.0-alastria/cakeshop.war
    dest: '{{ project_path }}/../cakeshop/cakeshop.war'

- name: Start Cakeshop
  command: |
    java -jar {{ project_path }}/../cakeshop/cakeshop.war
  async: 3600
  poll: 0
  args:
    chdir: '{{ project_path }}/../cakeshop'
