---

- name: Clone and update the eth_netstats repo
  git:
    repo: '{{ eth_netstats_repo }}'
    dest: '{{ project_path }}/eth-netstats'
    version: '{{ eth_netstats_version }}'
    force: yes
    accept_hostkey: yes

- name: Create logs folder for ethstats
  file:
    path: '{{ project_path }}/eth-netstats/logs'
    state: directory
    mode: '0755'

- name: Install dependencies
  npm:
    path: '{{ project_path }}/eth-netstats'

- name: Install grunt
  become: yes
  npm:
    name: '{{ item }}'
    global: yes
    state: present
  with_items:
    - grunt-cli
    - pm2

- name: Grunt
  command: grunt
  args:
    chdir: '{{ project_path }}/eth-netstats'

- name: Start
  command: pm2 start server.js >> {{ project_path }}/logs/netstat_{{ logdatetime }}.log &
  args:
    chdir: '{{ project_path }}/eth-netstats'
  environment:
    WS_SECRET: '{{ eth_netstats_secret }}'
