---

- name: Create password file for Geth account
  copy:
    dest: "{{ project_path }}/../.account_pass"
    content:
        "{{ etherbase_account_pass }}"

- name: Etherbase account
  command: geth --datadir ~/alastria/data --password "{{ project_path }}/../.account_pass" account new
  register: account

- set_fact:
    etherbase_account: "{{ account.stdout | regex_search(regexp,'\\1') }}"
  vars:
    regexp: 'Address: \{([a-f0-9]+)\}'

- debug: var=etherbase_account
