---
- hosts: all
  remote_user: ubuntu

  tasks:
    - import_tasks: install.yml
    - import_tasks: bootstrap.yml
    - import_tasks: eth_netstats.yml
    - import_tasks: nodes.yml
    - import_tasks: cakeshop.yml
