name: CI

on: [push]

jobs:
  backend:
    name: Build on ${{ matrix.container }}
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      matrix:
        container: [ 'williamyeh/ansible:ubuntu16.04', 'williamyeh/ansible:ubuntu16.04' ]

    steps:
    - uses: actions/checkout@v1

    - name: Install Ansible Galaxy
      run: ansible-galaxy install fubarhouse.golang

    - name: Run Ansible test
      run: cd infrastructure/ansible && ansible-playbook test.yml
