
version: '3'

networks:
  alastrianetwork:
    driver: bridge

services:
  validator1:
    networks:
      - alastrianetwork
    ports:
      - "22000:22000"
    image: alastria/validator
  #   environment:
  #     POSTGRES_PASSWORD: somepassword
  #     COMPOSE_PROJECT_NAME: serverstack

  # app2:
  #   networks:
  #     - mynetwork
  #   environment:
  #     COMPOSE_PROJECT_NAME: serverstack
  #   depends_on:
  #     - app1